[package]
authors = ["Nerry <108566+neri@users.noreply.github.com>"]
edition = "2024"
name = "wami"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
wami_macro = {path="./lib/wami_macro"}
leb128 = {path="./lib/leb128"}

libm = {version="0.2.11"}
smallvec = {version = "1.13.2", default-features = false}

[dev-dependencies]
wa_asm = { path = "./lib/wa_asm" }

[workspace]
members = [
  "example/cli",
  "example/hello",
  "tools/wat2wasm",
  "lib/wami_macro",
  "lib/leb128",
  "lib/wa_asm",
]
