[package]
authors = ["Nerry <108566+neri@users.noreply.github.com>"]
edition = "2024"
name = "wami"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
leb128 = {path="./lib/leb128"}
libwat2wasm = { path = "./lib/libwat2wasm" }
wami_macro = {path="./lib/wami_macro"}

libm = {version="0.2.13"}
smallvec = {version = "1.15.0", default-features = false}

[workspace]
members = [
  "example/cli",
  "example/hello",
  "tools/wat2wasm",
  "lib/wami_macro",
  "lib/leb128",
  "lib/libwat2wasm",
]
